/*
 * process_server_macro.h
 *
 *  Created on: Jun 13, 2014
 *      Author: marina
 */

#ifndef PROCESS_SERVER_MACRO_H_
#define PROCESS_SERVER_MACRO_H_

#define PROCESS_SERVER_CLONE_SUCCESS 0
#define PROCESS_SERVER_CLONE_FAIL 1

#define REPLICATION_STATUS_VALID 3
#define REPLICATION_STATUS_WRITTEN 1
#define REPLICATION_STATUS_INVALID 2
#define REPLICATION_STATUS_NOT_REPLICATED 0

#define VMA_OP_NOP 0
#define VMA_OP_UNMAP 1
#define VMA_OP_PROTECT 2
#define VMA_OP_REMAP 3
#define VMA_OP_MAP 4
#define VMA_OP_BRK 5

#define VMA_OP_SAVE -70
#define VMA_OP_NOT_SAVE -71

#define EXIT_ALIVE 0
#define EXIT_THREAD 1
#define EXIT_PROCESS 2
#define EXIT_FLUSHING 3

#define PARTIAL_VMA_MANAGEMENT 0
#define NOT_REPLICATED_VMA_MANAGEMENT 1

#define FOR_2_KERNELS 1
#define DIFF_PAGE 0

#if !FOR_2_KERNELS
#undef DIFF_PAGE
#define DIFF_PAGE 0
#endif

#define SUPPORT_FOR_CLUSTERING

#define MIGRATE_FPU 0

//#define MAX_KERNEL_IDS NR_CPUS
#define MAX_KERNEL_IDS 2
#endif /* PROCESS_SERVER_MACRO_H_ */
