obj-$(CONFIG_PCIE_DW) += pcie-designware.o
obj-$(CONFIG_PCI_EXYNOS) += pci-exynos.o
obj-$(CONFIG_PCI_MVEBU) += pci-mvebu.o
obj-$(CONFIG_PCI_TEGRA) += pci-tegra.o
obj-$(CONFIG_PCI_XGENE) += pci-xgene.o
obj-${CONFIG_PCI_XGENE_HOTPLUG} += pci-xgene-hotplug.o
obj-$(CONFIG_PCI_XGENE_MSI) += pci-xgene-msi.o
