#
# Makefile for APM X-GENE Classifier driver.
#

xgene-cle-objs :=		\
		apm_cle_access.o 	\
		apm_preclass_base.o   	\
		apm_preclass_api.o    	\
                apm_avl_base.o        	\
                apm_avl_api.o         	\
		apm_cle_mgr.o           \
		apm_cle_config.o

obj-$(CONFIG_XGENE_CLE) += xgene-cle.o
