#
# Makefile for the linux kernel.
#

# Common support
obj-y          			+= xgene_suspend_asm.o
obj-$(CONFIG_CPU_IDLE)          += xgene_cpuidle.o
obj-$(CONFIG_CPU_IDLE)		+=idmap.o
obj-$(CONFIG_SUSPEND)		+=suspend.o
